### ISSUE TITLE
LivelyFS crashes server

### ISSUE THREAD

**Issue by timfel** [LivelyKernel/LivelyKernel#299]
```
[2015-04-14 16:29:38.428] [ERROR] console - LivelyFS encountered error:  'TypeError: Cannot call method \'toString\' of null
    at Repository.util._extend.d.bindMethods.startReadingRequestContent (/home/tfelgentreff/babelsberg-js/LivelyKernel/node_modules/life_star/node_modules/lively-davfs/repository.js:200:63)
    at Repository.b [as startReadingRequestContent] (domain.js:183:18)
    at Repository.util._extend.d.bindMethods.captureDAVEvt (/home/tfelgentreff/babelsberg-js/LivelyKernel/node_modules/life_star/node_modules/lively-davfs/repository.js:161:26)
    at Repository.b [as captureDAVEvt] (domain.js:183:18)
    at Repository.util._extend.d.bindMethods.onFileCreation (/home/tfelgentreff/babelsberg-js/LivelyKernel/node_modules/life_star/node_modules/lively-davfs/repository.js:172:14)
    at Repository.b [as onFileCreation] (domain.js:183:18)
    at EventEmitter.emit (events.js:95:17)
    at EventEmitter.module.exports.jsDAVPlugin.extend.beforeCreateFile (/home/tfelgentreff/babelsberg-js/LivelyKernel/node_modules/life_star/node_modules/lively-davfs/jsDAV-plugin.js:91:14)
    at /home/tfelgentreff/babelsberg-js/LivelyKernel/node_modules/life_star/node_modules/lively-davfs/node_modules/jsDAV/lib/shared/asyncEvents.js:57:22
    at handler (/home/tfelgentreff/babelsberg-js/LivelyKernel/node_modules/life_star/node_modules/lively-davfs/node_modules/jsDAV/node_modules/asyncjs/lib/async.js:148:21)'
```

**Comment by timfel** [comment]
Reproducible on lively-kernel.org/babelsberg by creating a  callback.html from the SystemBrowser when using HTTPS
